### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by haydenadams** [wschwab/language-vyper#2]
Is this working? If so, some basic install instructions would be helpful!

**Comment by wschwab** [comment]
@haydenadams My apologies - I hadn't seen this for the roughly year it was up. While I have my doubts that you're still looking to use the project, I would like to answer: I'm getting back to actively working on this now, and hope to publish it as an official Atom package, making install easier.

If you want to use it now, firstly I would wait until I've updated it a bit (in the works), but here's how you'd do it (using the GUI):
1) clone the repo locally
2) in Atom, go to the Packages menu, and click on 'Package Generator'
3) select the 'language-vyper' folder you just cloned
4) restart Atom (it won't load the package until the next time it runs)

Thanks for your interest!

**Comment by wschwab** [comment]
Project now updated. Use the above if you're interested in using. Feel free to get back in touch if anything isn't working right, or with suggestions/feedback!
